### ISSUE TITLE
Fatal error: spawn ENOENT when trying to run multishot

### ISSUE THREAD

**Issue by trevorpolischuk** [firstandthird/grunt-multishot#1]
Hello, 

This Grunt plugin appears to do exactly what I need. I would like to feed it a list of URLs in my Gruntfile (essentially every page of my project) so I could quickly generate screenshots of everything. 

However, I can't get it off the ground. 

running `grunt multishot --debug` returns `Running "multishot:default" (multishot) task
[D] Task source: /path/to/project/user-guides/node_modules/grunt-multishot/tasks/multishot.js
Fatal error: spawn ENOENT` 

I tried looking through multishot.js but, I honestly have no idea what is failing or how to test what's failing. 

Here is a copy of my Gruntfile.js 

`module.exports = function(grunt) {

```
grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),   
    connect: {
        server: {
            options: {
                hostname: 'user-guides',
                port: 80,
                base: 'public'
            }
        }
    },
    jshint: {
        all: ['Gruntfile.js', 'public/assets/js/helper/*.js', 'public/assets/js/specific/*.js']
    },
    qunit: {
        all: {
            options: {
                timeout: 5000,
                urls: [
                'http://user-guides:80/test/test.html',
                ]
            }
        }
    },
    multishot: {
        default: {
            temp: '/tmp/multishot/',
            output: '/tmp/multishot/',
            url: ['http://google.com', 'http://yahoo.com', 'http://facebook.com', 'http://digg.com', 'http://amazon.com']
        }
    }
}
);

grunt.loadNpmTasks('grunt-contrib-jshint');
grunt.loadNpmTasks('grunt-contrib-qunit');
grunt.loadNpmTasks('grunt-contrib-connect');
grunt.loadNpmTasks('grunt-multishot');

grunt.registerTask('test', ['connect', 'qunit']);
```

};`

Any help is greatly appreciated

**Comment by dawnerd** [comment]
I actually ran into this yesterday too. I'll get a fix up today.

**Comment by dawnerd** [comment]
Figured out the cause. I never put the dependencies in the readme.

You need this http://www.paulhammond.org/webkit2png/

Sorry about that!

**Comment by trevorpolischuk** [comment]
Thanks, ill check out the plugin again when I get a chance.
